name = "auth2"
main = "src/server.ts"
compatibility_date = "2024-12-09"
node_compat = true

account_id = "0c8c22bdcd98c3dc6a35190650ef7906"

services = [
    { binding = "TOKEN_SERVICE", service = "token-service-dev" },
    { binding = "JWKS_SERVICE", service = "token-service-dev" },
]

routes = [
    { pattern = "auth2.sesamy.dev/*", zone_id = "b56a76d859fe2ed6a8d77270cd2e8ba8" },
    { pattern = "*.auth2.sesamy.dev/*", zone_id = "b56a76d859fe2ed6a8d77270cd2e8ba8" },
]

[vars]
IMAGE_PROXY_URL = "https://imgproxy.prod.sesamy.cloud"
ISSUER = "https://auth2.sesamy.dev/"
API_URL = 'https://api.sesamy.dev'
AUTH_URL = 'https://token.sesamy.dev'
JWKS_URL = "https://token.sesamy.dev/.well-known/jwks.json"
SAML_SIGN_URL = "https://api.sesamy.dev/profile/saml/sign"
READ_PERMISSION = "auth:read"
WRITE_PERMISSION = "auth:write"
ENVIRONMENT = 'dev'
DEFAULT_TENANT_ID = 'DEFAULT_SETTINGS'
DEFAULT_CLIENT_ID = 'DEFAULT_CLIENT'


[observability]
enabled = true

[triggers]
crons = ["*/30 * * * *"]

[env.production]
account_id = "d684d0f34602a66c97de230566a2fa87"
workers_dev = true
services = [
    { binding = "TOKEN_SERVICE", service = "token-service-prod" },
    { binding = "JWKS_SERVICE", service = "token-service-prod" },
]
# if we use multiple routes on dev then change this
# routes = [
#     { pattern = "auth2.sesamy.com/*", zone_id = "b944b5871689ada6ce48e380968a06b5" },
# ]
route = { pattern = "auth2.sesamy.com/*", zone_id = "b944b5871689ada6ce48e380968a06b5" }

[env.production.vars]
ISSUER = "https://auth2.sesamy.com/"
API_URL = 'https://api.sesamy.com'
AUTH_URL = 'https://token.sesamy.com'
JWKS_URL = "https://token.sesamy.com/.well-known/jwks.json"
SAML_SIGN_URL = "https://api.sesamy.dev/profile/saml/sign"
READ_PERMISSION = 'auth:read'
WRITE_PERMISSION = 'auth:write'
ENVIRONMENT = 'prod'
IMAGE_PROXY_URL = "https://imgproxy.prod.sesamy.cloud"
DEFAULT_TENANT_ID = 'DEFAULT_SETTINGS'
DEFAULT_CLIENT_ID = 'DEFAULT_CLIENT'

[env.production.observability]
enabled = true

[env.production.triggers]
crons = ["0 3 * * *"]
