name: Unit tests

on: pull_request

jobs:
  node-test:
    runs-on:
      - self-hosted
      - X64
    container: node:18.13
    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v3
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

      - name: Install dependencies
        run: yarn
        env:
          NODE_AUTH_TOKEN: ${{ secrets.PACKAGE_READ_TOKEN }}

      - run: yarn lint
      - run: yarn format:ci-cd
      - run: yarn build
      - run: yarn test
      - run: yarn integration
